### ISSUE TITLE
URL Calling Issue

### ISSUE THREAD

**Issue by macjeff** [jimboca/udi-wirelesstag-poly#36]
I sent you a PM but wanted to create an issue.  Over the weekend my Red Exclamation point was coming on SOLID on the tag manager.  I tried everything and could not get it to work.  

I did do an update this morning of your Node Server and now its working a lot better.

Meanwhile, the wireless tag support people said the solid RED are a problem with a URL call.  So I looked an 100% of my URL calls are pointing to my polisy and I did not create a single one.

So I have to assume your node server created them all.

They said delete them all and recreate will get rid of the bad one causing the issue but worried that will mess up your node server.

And maybe your latest update (went from .17 to .20) actually fixed the issue since I am not seeing the issue anymore.   But he said I have way too many URL calls in my account.  Again they are all pointing to polisy and I did not create them!!

Hope you can shed some light on this.

**Comment by jimboca** [comment]
Well, that's how the nodes has always worked, there are no changes related to URL calling. My guess would be the tag manager was having issues communicating with Polyglot. Restarting the nodeserver resets all the URL calling paths.

**Comment by macjeff** [comment]
Wireless tag tech support says since I switched out some tags they are thinking some of the URL's are not needed and want to delete them all and start again.  Can I ok that and then just restart the ISY and it will make them again.

Also for example my Mailbox tag.  I use it for Open Close status ONLY.  Dont care about temp or humidity in my mailbox.  But I see URL calls for those.  Should I uncheck the URL calls I dont need or everytime I restart the Nodeserver it will recreate them?

**Comment by jimboca** [comment]
Yes, you can delete them all and restart will recreate them.  I can't remember if restarting deletes them all as well before creating them, but I don't think it does.  Also I need to think about clearing them out for a tag when you delete it.  That sounds like the real issue here?

**Comment by macjeff** [comment]
I think there are a few issues.  Was told the limit is 200 calls and you will have issues.  I have a dozen tags and there are a lot of url calls I don’t need but not 200.  

And also deleting a tag. 

But the main issue was why it would stay on red exclamation for a while and nothing would work with the tags.  Then randomly it would go off (not red) and things would work for 10 seconds or so.  In fact it would catch up with all my tag notifications.  Then it would go red again.  So the tags were pretty useless.  That was Friday.  Saturday.  And Sunday and then today it was fine.  So I guess updating your node server forced the node server restart.   

Is there a way to automate a restart of a node server from Polisy.   That may help   Afraid it may happen again and I could auto start at like 2 am.  

Only thought on how this happened was maybe a power outage we did have Thursday night and internet outage on Friday morning due to storms.  Maybe this caused polisy urls not to work.   

That’s all my thoughts but it’s working now.
