### ISSUE TITLE
Battery Change Required Query?

### ISSUE THREAD

**Issue by macjeff** [jimboca/udi-wirelesstag-poly#37]
Background info---

I have a unit in my freezer and because of the cold it drains quickly.  Its also exponential so the lower the battery gets the faster it drains.  It was about 2 months in and fine and last night it was at 20%.  at 4 am 10% and at 8 am it was at 2% and no longer reporting.  I have a program that reports it temp is too high in freezer by sounding an insteon alarm.
Before it went dead it sent a reading of 60 degrees that was bogus.  That set off an alarm but its ok.

Problem---
Replaced battery.  I changed batteries and went to app and did an update.  App now showed 104 percent battery and 40 degrees.  I put it in the freezer and watched it go down below 30 so we are ok.

About 20 min later I got an alarm again too high.  Went to the ISY to see why and battery showed 4% and 60 degrees.  So it must have got a report just before it went dead so about 30-45 min ago.  all i did is hit QUERY and the correct data came in.

Do I have to do that every time I change a battery?  The data was correct in the app so why did the ISY not pick it up?

Let me know if you have any ideas or suggestions.  Its ok now.,  Just asking this for next time.

**Comment by jimboca** [comment]
I have no control over what updates are pushed from the hub to the Polyglot Node Server.  Please ask on the wireless tags users list if there is a way to have battery updates pushed out with url calling method.

**Comment by macjeff** [comment]
I asked my contact there.   Will reply soon

**Comment by jimboca** [comment]
There is only one contact there :) He replies on the user list fairly often and that makes it public knowledge which is why I suggested that... But let me know what he says.

**Comment by macjeff** [comment]
Funny I do realize its the same guy all the time but he always says WE will take care of that so it made me think they had a lot of others.

**Comment by macjeff** [comment]
this is what he sent me

If you click "URL calling" the "custom URL calling... " display reads "When tag sends a temperature/humidity/brightness update - {0}: Tag name, {1}: Tag ID, {2}: temperature in °C, {3}: humidity/moisture (%), {4}: brightness (lux), {5}: timestamp, {6}: battery voltage" so {6} is the battery voltage.

**Comment by jimboca** [comment]
Well, that's crazy, wonder if they added that or I totally missed it.  Will add when I have some free time.
